RSpec/ChangeByZero:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - as
    - by
    - for
    - given
    - having
    - when
    - with
    - without

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/Output:
  Exclude:
    - '**/spec_helper.rb'
    - 'spec/support/*.rb'

RSpec/ReturnFromStub:
  EnforcedStyle: block

RSpec/StubbedMock:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false
